"""habit reset counter default

Revision ID: 07f61cd1953e
Revises: ec72ee48fbf4
Create Date: 2024-03-28 09:53:17.408666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f61cd1953e'
down_revision = 'ec72ee48fbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
