"""habit history

Revision ID: 0b01460ccfad
Revises: 0e31f5162021
Create Date: 2024-03-28 14:05:52.844407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b01460ccfad'
down_revision = '0e31f5162021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
