"""habit history relationship

Revision ID: 0e31f5162021
Revises: c816ab80c053
Create Date: 2024-03-28 12:57:50.586368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e31f5162021'
down_revision = 'c816ab80c053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
