"""todo table

Revision ID: aa3f3a2ed9c9
Revises: 6238eb23ed3f
Create Date: 2024-04-01 12:32:33.693771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3f3a2ed9c9'
down_revision = '6238eb23ed3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do', sa.Column('status', sa.Enum('active', 'deleted', 'new', 'completed', name='statusenum'), nullable=True))
    op.drop_column('to_do', 'isCompleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do', sa.Column('isCompleted', sa.BOOLEAN(), nullable=True))
    op.drop_column('to_do', 'status')
    # ### end Alembic commands ###
