"""habit history table

Revision ID: c816ab80c053
Revises: 07f61cd1953e
Create Date: 2024-03-28 12:10:43.785750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c816ab80c053'
down_revision = '07f61cd1953e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('reset_counter', sa.Enum('daily', 'weekly', 'monthly', name='resetcounterenum'), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('habit_daily')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_daily',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('habit_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('habit_history')
    # ### end Alembic commands ###
