"""todo removed fk

Revision ID: e934652e4139
Revises: 7be76ad19c3a
Create Date: 2024-03-06 14:27:39.277522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e934652e4139'
down_revision = '7be76ad19c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
