"""habit reset counter

Revision ID: ec72ee48fbf4
Revises: 36cd842bffba
Create Date: 2024-03-28 09:38:22.726389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec72ee48fbf4'
down_revision = '36cd842bffba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('reset_counter', sa.Enum('daily', 'weekly', 'monthly', name='resetcounterenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'reset_counter')
    # ### end Alembic commands ###
