"""date_created_habit

Revision ID: 0bc985f2d5be
Revises: aa3f3a2ed9c9
Create Date: 2024-07-17 09:00:44.351837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc985f2d5be'
down_revision = 'aa3f3a2ed9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('counter_option', sa.Enum('daily', 'weekly', 'monthly', name='counteroptionenum'), nullable=True))
    op.drop_column('habit', 'reset_counter')
    op.add_column('habit_events', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_events', 'note')
    op.add_column('habit', sa.Column('reset_counter', sa.VARCHAR(length=7), nullable=True))
    op.drop_column('habit', 'counter_option')
    # ### end Alembic commands ###
