"""habit table status

Revision ID: 6238eb23ed3f
Revises: e56f186e5016
Create Date: 2024-04-01 10:45:22.386012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6238eb23ed3f'
down_revision = 'e56f186e5016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('status', sa.Enum('deleted', 'new', 'completed', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'status')
    # ### end Alembic commands ###
